package com.epam.gym.web.controller;

import com.epam.gym.entity.Trainee;
import com.epam.gym.entity.Trainer;
import com.epam.gym.service.TraineeService;
import com.epam.gym.web.dto.ActivateDeactivateRequest;
import com.epam.gym.web.dto.RegisterTraineeRequest;
import com.epam.gym.web.dto.RegistrationResponse;
import com.epam.gym.web.dto.TraineeProfileResponse;
import com.epam.gym.web.dto.TraineeTrainingResponse;
import com.epam.gym.web.dto.TrainerShortResponse;
import com.epam.gym.web.dto.UpdateTraineeProfileRequest;
import com.epam.gym.web.dto.UpdateTraineeTrainersRequest;
import com.epam.gym.dto.TraineeTrainingCriteria;
import com.epam.gym.web.security.AuthCredentials;
import com.epam.gym.metrics.GymMetrics;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiImplicitParam;
import io.swagger.annotations.ApiImplicitParams;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import jakarta.validation.Valid;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.util.List;

@RestController
@RequestMapping("/api/trainees")
@Validated
@Api(tags = "Trainee")
public class TraineeController {

    private final TraineeService traineeService;
    private final GymMetrics metrics;

    public TraineeController(TraineeService traineeService, GymMetrics metrics) {
        this.traineeService = traineeService;
        this.metrics = metrics;
    }

    @PostMapping
    @ApiOperation(value = "Register a new trainee", notes = "Public endpoint — no authentication required. "
            + "Username and password are generated by the server.")
    @ApiResponses(@ApiResponse(code = 201, message = "Trainee created"))
    public ResponseEntity<RegistrationResponse> register(@Valid @RequestBody RegisterTraineeRequest request) {
        Trainee trainee = traineeService.createTraineeProfile(
                request.getFirstName(), request.getLastName(), request.getDateOfBirth(), request.getAddress());
        metrics.incrementTraineeRegistrations();
        RegistrationResponse response = new RegistrationResponse(
                trainee.getUser().getUsername(), trainee.getUser().getPassword());
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @GetMapping("/{username}")
    @ApiOperation(value = "Get trainee profile", notes = "Requires HTTP Basic authentication as the trainee.")
    @ApiImplicitParams(@ApiImplicitParam(name = "Authorization", value = "Basic auth credentials",
            required = true, paramType = "header", dataTypeClass = String.class))
    public TraineeProfileResponse getProfile(@ApiParam(required = true) @PathVariable String username,
                                              AuthCredentials credentials) {
        Trainee trainee = traineeService.getProfileByUsername(username, credentials.getPassword());
        return TraineeProfileResponse.from(trainee);
    }

    @PutMapping("/{username}")
    @ApiOperation(value = "Update trainee profile", notes = "Requires HTTP Basic authentication as the trainee. "
            + "Username cannot be changed.")
    public TraineeProfileResponse updateProfile(@ApiParam(required = true) @PathVariable String username,
                                                 @Valid @RequestBody UpdateTraineeProfileRequest request,
                                                 AuthCredentials credentials) {
        Trainee trainee = traineeService.updateProfile(username, credentials.getPassword(),
                request.getFirstName(), request.getLastName(), request.getDateOfBirth(), request.getAddress(),
                Boolean.TRUE.equals(request.getIsActive()));
        return TraineeProfileResponse.from(trainee);
    }

    @DeleteMapping("/{username}")
    @ApiOperation(value = "Delete trainee profile", notes = "Hard delete; cascades the trainee's trainings. "
            + "Requires HTTP Basic authentication as the trainee.")
    public ResponseEntity<Void> deleteProfile(@ApiParam(required = true) @PathVariable String username,
                                               AuthCredentials credentials) {
        traineeService.deleteProfileByUsername(username, credentials.getPassword());
        return ResponseEntity.ok().build();
    }

    @GetMapping("/{username}/unassigned-trainers")
    @ApiOperation(value = "Get active trainers not yet assigned to this trainee",
            notes = "Requires HTTP Basic authentication as the trainee.")
    public List<TrainerShortResponse> getUnassignedTrainers(@ApiParam(required = true) @PathVariable String username,
                                                              AuthCredentials credentials) {
        List<Trainer> trainers = traineeService.getTrainersNotAssigned(username, credentials.getPassword());
        return trainers.stream().map(TrainerShortResponse::from).toList();
    }

    @PutMapping("/{username}/trainers")
    @ApiOperation(value = "Replace the trainee's trainer list",
            notes = "Requires HTTP Basic authentication as the trainee.")
    public List<TrainerShortResponse> updateTrainers(@ApiParam(required = true) @PathVariable String username,
                                                       @Valid @RequestBody UpdateTraineeTrainersRequest request,
                                                       AuthCredentials credentials) {
        List<Trainer> trainers = traineeService.updateTrainersList(
                username, credentials.getPassword(), request.getTrainers());
        return trainers.stream().map(TrainerShortResponse::from).toList();
    }

    @GetMapping("/{username}/trainings")
    @ApiOperation(value = "Get the trainee's trainings list, with optional filters",
            notes = "Requires HTTP Basic authentication as the trainee.")
    public List<TraineeTrainingResponse> getTrainings(
            @ApiParam(required = true) @PathVariable String username,
            @ApiParam("Inclusive lower bound on training date")
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate periodFrom,
            @ApiParam("Inclusive upper bound on training date")
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate periodTo,
            @ApiParam("Filter by trainer's last name") @RequestParam(required = false) String trainerName,
            @ApiParam("Filter by training type name") @RequestParam(required = false) String trainingType,
            AuthCredentials credentials) {
        TraineeTrainingCriteria criteria = new TraineeTrainingCriteria();
        criteria.setFromDate(periodFrom);
        criteria.setToDate(periodTo);
        criteria.setTrainerName(trainerName);
        criteria.setTrainingTypeName(trainingType);
        return traineeService.getTrainingsList(username, credentials.getPassword(), criteria).stream()
                .map(TraineeTrainingResponse::from)
                .toList();
    }

    @PatchMapping("/{username}/status")
    @ApiOperation(value = "Activate or de-activate a trainee",
            notes = "Not idempotent: requesting the account's current state is rejected. "
                    + "Requires HTTP Basic authentication as the trainee.")
    public ResponseEntity<Void> setActive(@ApiParam(required = true) @PathVariable String username,
                                           @Valid @RequestBody ActivateDeactivateRequest request,
                                           AuthCredentials credentials) {
        traineeService.setActive(username, credentials.getPassword(), Boolean.TRUE.equals(request.getIsActive()));
        return ResponseEntity.ok().build();
    }
}
