package com.epam.gym.web.controller;

import com.epam.gym.dto.TrainerTrainingCriteria;
import com.epam.gym.entity.Trainer;
import com.epam.gym.service.TrainerService;
import com.epam.gym.web.dto.ActivateDeactivateRequest;
import com.epam.gym.web.dto.RegisterTrainerRequest;
import com.epam.gym.web.dto.RegistrationResponse;
import com.epam.gym.web.dto.TrainerProfileResponse;
import com.epam.gym.web.dto.TrainerTrainingResponse;
import com.epam.gym.web.dto.UpdateTrainerProfileRequest;
import com.epam.gym.web.security.AuthCredentials;
import com.epam.gym.metrics.GymMetrics;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiImplicitParam;
import io.swagger.annotations.ApiImplicitParams;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import jakarta.validation.Valid;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.util.List;

@RestController
@RequestMapping("/api/trainers")
@Validated
@Api(tags = "Trainer")
public class TrainerController {

    private final TrainerService trainerService;
    private final GymMetrics metrics;

    public TrainerController(TrainerService trainerService, GymMetrics metrics) {
        this.trainerService = trainerService;
        this.metrics = metrics;
    }

    @PostMapping
    @ApiOperation(value = "Register a new trainer", notes = "Public endpoint — no authentication required. "
            + "Username and password are generated by the server.")
    @ApiResponses(@ApiResponse(code = 201, message = "Trainer created"))
    public ResponseEntity<RegistrationResponse> register(@Valid @RequestBody RegisterTrainerRequest request) {
        Trainer trainer = trainerService.createTrainerProfile(
                request.getFirstName(), request.getLastName(), request.getSpecialization());
        metrics.incrementTrainerRegistrations();
        RegistrationResponse response = new RegistrationResponse(
                trainer.getUser().getUsername(), trainer.getUser().getPassword());
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @GetMapping("/{username}")
    @ApiOperation(value = "Get trainer profile", notes = "Requires HTTP Basic authentication as the trainer.")
    @ApiImplicitParams(@ApiImplicitParam(name = "Authorization", value = "Basic auth credentials",
            required = true, paramType = "header", dataTypeClass = String.class))
    public TrainerProfileResponse getProfile(@ApiParam(required = true) @PathVariable String username,
                                              AuthCredentials credentials) {
        Trainer trainer = trainerService.getProfileByUsername(username, credentials.getPassword());
        return TrainerProfileResponse.from(trainer);
    }

    @PutMapping("/{username}")
    @ApiOperation(value = "Update trainer profile", notes = "Requires HTTP Basic authentication as the trainer. "
            + "Username cannot be changed; specialization is read-only.")
    public TrainerProfileResponse updateProfile(@ApiParam(required = true) @PathVariable String username,
                                                 @Valid @RequestBody UpdateTrainerProfileRequest request,
                                                 AuthCredentials credentials) {
        Trainer trainer = trainerService.updateProfile(username, credentials.getPassword(),
                request.getFirstName(), request.getLastName(), Boolean.TRUE.equals(request.getIsActive()));
        return TrainerProfileResponse.from(trainer);
    }

    @GetMapping("/{username}/trainings")
    @ApiOperation(value = "Get the trainer's trainings list, with optional filters",
            notes = "Requires HTTP Basic authentication as the trainer.")
    public List<TrainerTrainingResponse> getTrainings(
            @ApiParam(required = true) @PathVariable String username,
            @ApiParam("Inclusive lower bound on training date")
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate periodFrom,
            @ApiParam("Inclusive upper bound on training date")
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate periodTo,
            @ApiParam("Filter by trainee's last name") @RequestParam(required = false) String traineeName,
            AuthCredentials credentials) {
        TrainerTrainingCriteria criteria = new TrainerTrainingCriteria();
        criteria.setFromDate(periodFrom);
        criteria.setToDate(periodTo);
        criteria.setTraineeName(traineeName);
        return trainerService.getTrainingsList(username, credentials.getPassword(), criteria).stream()
                .map(TrainerTrainingResponse::from)
                .toList();
    }

    @PatchMapping("/{username}/status")
    @ApiOperation(value = "Activate or de-activate a trainer",
            notes = "Not idempotent: requesting the account's current state is rejected. "
                    + "Requires HTTP Basic authentication as the trainer.")
    public ResponseEntity<Void> setActive(@ApiParam(required = true) @PathVariable String username,
                                           @Valid @RequestBody ActivateDeactivateRequest request,
                                           AuthCredentials credentials) {
        trainerService.setActive(username, credentials.getPassword(), Boolean.TRUE.equals(request.getIsActive()));
        return ResponseEntity.ok().build();
    }
}
